#!/usr/bin/perl -w
#
## Check available GPUs. Feng
#
use File::Basename;

# First let's get the temporature of the GPUs of all nodes:
#
#sorted already, so the first gpu of a node in the array is the hotest one.
#chage here fit your gpu nodes
my $gpunodes= "node[001-012,018,019]";
my @gpuinfo=`pdsh -w $gpunodes nvidia-smi   --query-gpu=gpu_name,gpu_bus_id,temperature.gpu,memory.used,utilization.gpu,utilization.memory --format=csv,noheader|awk -F "," '{split(\$1,node,":"); print node[1] " ; "\$3}'|sort -r`;;

#Get GPU nodes. Should ignore CPU nodes now.

my @nodes=`sinfo -a --Node -o "%.10N %8O %c %.10m %.10e  %.6t  %G"|uniq|grep -v -e down|grep gpu`;;

#print header info
printf("     NODE     LOAD    CPUS    MEMORY(GB)   STATE     GRES           Hi-Temporature\n");

#loop to process each gpu node
foreach $node (@nodes)
{
  my $found=0;
  chomp($node);

  my @vals=split(/\s+/,$node);
  #
  #$node, $load, $cpus, $memtot,$memfree,$state,$gres
  #update format, unit.
  $vals[4]=int($vals[4]/1000); #Convert from MB to GB
  $vals[5]=int($vals[5]/1000); #Convert from MB to GB

  #Get Allocated resource info of the current node.
  my @computes=`scontrol show node $vals[1]|grep AllocTRES`;;
  foreach $comp (@computes)
  {
    chomp($comp);
    # 
    my @alloc=split(/AllocTRES=/,$comp);
    # 
    # Init allocated res info.
    my @res=(0,0); my @cpu=(0,0); my @mem=(0,0);my @gpu=(0,0);
    #the hotest GPU's temporature
    my $temp = 0;
    if (defined $alloc[1] and length $alloc[1]){
       # 
       @res=split(/,/,$alloc[1]);
       @cpu=split(/=/,$res[0]);
       @mem=split(/=/,$res[1]);

       if(index($mem[1], "M") != -1) {
          chop($mem[1]); #remove trailing M char.
          $memalloc = int($mem[1]/1000);#convert from MB to GB.
       }
       elsif (index($mem[1], "G") != -1) {
           chop($mem[1]); #remove trailing G char.
           $memalloc = int($mem[1]);
       }
       #TB RAM?
       @gpu=split(/=/,$res[2]);
    }
    #my @aaa = split(/ ;  /,$gpuinfo[1],2);
    foreach $line  (@gpuinfo)
    {
      my @gtemp=split(/ ;  /,$line); 
      # 
      if ($gtemp[0] eq $vals[1]){
        $temp=$gtemp[1];
	      chomp($temp);
	      last;
      }
    }
    printf("%10s %6.2f %5d/%2d   %3s/%3s/%3s %6s %3s/%-22s  %3s\n",$vals[1],$vals[2],$cpu[1],$vals[3],$memalloc,$vals[5],$vals[4],$vals[6],$gpu[1],$vals[7],$temp)
   
  }
}
printf("CPUS lists allocated/total CPU cores. \n");
printf("MEMORY(GB) lists allocated/free/total memory in GB. \n");
printf("GRES lists allocated/total GPUs. \n");
